# Generated by Django 6.0.3 on 2026-04-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_creativeitem_created_at_creativeitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativeitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='creativeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='creative_gallery/'),
        ),
    ]
