# Generated by Django 6.0.3 on 2026-05-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_remove_creativeitem_image_url_creativeitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='task',
            name='secure_handshake_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
